# Exercises for the course _"Intro to Numerical Computing with NumPy (Beginner) | SciPy 2018 Tutorial | Alex Chabot-Leclerc"_

Link https://www.youtube.com/watch?v=V0D2mhVt7NE&t=2592s

### Exercise 1

In [1]:
import numpy as np

In [2]:
b = np.array([0,1,2,3])

In [3]:
b*5

array([ 0,  5, 10, 15])

In [4]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
a = np.arange(25).reshape(5,5)

Make the slices asked for in ex. 1

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
a[-1,:]

array([20, 21, 22, 23, 24])

In [9]:
a[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [11]:
a[1::2,:-2:2]

array([[ 5,  7],
       [15, 17]])

### Rough notes in between

In [12]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [13]:
mask2 = a<30
mask2

array([ True,  True,  True, False, False, False, False, False])

In [14]:
a[mask2]

array([ 0, 10, 20])

In [15]:
mask =np.array([0,1,1,0,0,1,0,0], dtype = bool)
a[mask]

array([10, 20, 50])

In [16]:
mask3 = [1,2,-3]
a[mask3]

array([10, 20, 50])

In [17]:
a = np.array([3,-1,-2,4,-6,8])
negatives = a<0
a[negatives]

array([-1, -2, -6])

In [18]:
a[a<0] =0
a

array([3, 0, 0, 4, 0, 8])

Bitwise operators: and, or not

& (and), | (or), ~(not), ^(xor)

xor

   
   OR
   T / F
T| T   T
F| T   F


   XOR
   T/ F
T| F  T
F| T  F

In [19]:
a[(a>3) & (a<8)]

array([4])

In [20]:
a = np.array([30,1,2])
b = np.array([1,50,50])

a[a>b]

array([30])

### Exercise 2

In [21]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

select all diagonals

In [22]:
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [23]:
a[a%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [24]:
#alternative ways of doing this
np.where(a%3==0,a,np.nan)

array([[ 0., nan, nan,  3., nan],
       [nan,  6., nan, nan,  9.],
       [nan, nan, 12., nan, nan],
       [15., nan, nan, 18., nan],
       [nan, 21., nan, nan, 24.]])

In [25]:
output = np.empty_like(a,dtype='float')
output.fill(np.nan)
mask = (a%3==0)
output[mask] = a[mask]
output

array([[ 0., nan, nan,  3., nan],
       [nan,  6., nan, nan,  9.],
       [nan, nan, 12., nan, nan],
       [15., nan, nan, 18., nan],
       [nan, 21., nan, nan, 24.]])

### Notes in between

    Using nan values
    
    (They propogate like poison unless they are explicitly ignored using a numpy function that accounts for them)

In [26]:
np.nan + 6

nan

In [27]:
np.sum([np.nan, 1, 2, 3, 4, 5])

nan

In [28]:
np.mean([1,2,3,4,5,np.nan])

nan

In [29]:
#example of np.nan function
np.nanmean([1,2,3,4,5,np.nan])

3.0

In [30]:
#example of fancy indexing and then sum

a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
np.sum(a[a%3==0])

108

In [32]:
#example of function
np.sum(a[a>12])

222

In [33]:
#example of method
a[a>12].sum()

222

In [34]:
a.sum(axis=0)

array([50, 55, 60, 65, 70])

In [35]:
a.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [36]:
a.sum(axis = -1) #this is very useful!

array([ 10,  35,  60,  85, 110])

In [37]:
# a good way to check if you are operating along the correct axis. 
#Look at the shape before and after an operation. It will help you !

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
a.shape

(6, 4)

In [39]:
a.mean(axis = 1).shape

(6,)

In [40]:
a.mean(axis = 0).shape

(4,)

### Exercise 3

In [41]:
#for the following array

a = np.arange(-15,15).reshape(5,6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [42]:
#Compute the maximum of each row

a.max(axis=-1)


array([225,  81,   9,  64, 196], dtype=int32)

In [43]:
#Compute the mean of each column
a.mean(axis = 0)

array([81., 76., 73., 72., 73., 76.])

In [44]:
#The position of the overall maximum
a.argmax(axis=1)

array([0, 0, 0, 5, 5], dtype=int64)

In [45]:
a.argmax(axis=0)

array([0, 0, 0, 0, 4, 4], dtype=int64)

In [46]:
a.argmax()

0

In [47]:
a.flatten()

array([225, 196, 169, 144, 121, 100,  81,  64,  49,  36,  25,  16,   9,
         4,   1,   0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100,
       121, 144, 169, 196], dtype=int32)

In [48]:
a.flatten()[0]

225

In [49]:
b = np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
np.argmax(b)

24

In [51]:
b.flatten()[np.argmax(b)]

24

In [55]:
# numpy unravel function is also really useful for finding the position of this value !!!

#np.unravel_index?

row, col = np.unravel_index(24,b.shape)

np.unravel_index(24,b.shape)

(4, 4)

In [56]:
np.where?